Congenica/psga-pipeline-sars-cov-2

- jenkins/files/sars_cov_2/large_tests/Jenkinsfile
- jenkins/files/sars_cov_2/small_tests/Jenkinsfile
- jenkins/files/sars_cov_2/validation-ci/Jenkinsfile
- psga/sars_cov_2/psga.nf
**Changes:**
* if `--sequencing_technology` is `unknown` (=FASTA samples), then `--kit` must be `none`. In other words, primers are passed via `--kit` only for illumina / ont samples. The case where illumina/ont samples do not have any primers is not currently supported by the pipeline and is not part of this ticket.
**Tests:**
See jenkins for integration tests.
Here:
Incorrect input:
```
root@sars-cov-2-pipeline-minikube-5985485ddc-zdfkk:/app/psga# nextflow run . --run unknown_short --sequencing_technology unknown --kit ARTIC_V3 --metadata s3://synthetic-data-dev/UKHSA/small_tests/unknown/metadata.csv --output_path /data/output/unknown_short
N E X T F L O W  ~  version 22.08.0-edge
Launching `./main.nf` [elated_hypatia] DSL2 - revision: b450160779
--kit must be 'none' for FASTA samples …
```
> PSG-951: assign "none" to --kit if samples are fasta

- psga/sars_cov_2/ncov2019_artic.nf
- scripts/sars_cov_2/generate_pipeline_results_files.py
- tests/sars_cov_2/test_generate_pipeline_results_files.py
- tests/test_data/pipeline_results_files/resultfiles_illumina.json
- tests/test_data/pipeline_results_files/resultfiles_ont.json
**Changes:**
* add extra output generated by ncov. In particular:
a. collect primertrimmed.rg.sorted.bam and pass.vcf.gz for ont samples
b. collect mapped.primertrimmed.sorted.bam and variants.tsv for illumina samples
* remove `muscle.in.fa` and `muscle.out.fa` as these files are no longer generated following the update of the medaka model
This PR also fixes the integration tests: https://jenkins.services.congenica.net/job/psga-pipeline-sars-cov-2-small-tests/job/PSG-922_add_additional_output_files/5 
**Testing:**
```
root@sars-cov-2-pipeline-minikube-5985485ddc-zdfkk:/app/psga# nextflow run . --run ont_short --sequencing_technology ont --kit ARTIC_V3 --metadata /data/ont.csv --output_path /data/output/ont_short -resume
N E X T F L O W  ~  version 22.08.0-edge
Launching `./main.nf` …
```
> PSG-922: add bam and variant files to the list of ncov2019-artic published files

- Makefile
- jenkins/files/sars_cov_2/Jenkinsfile
- k8s/k8s_sars_cov_2.yaml
- minikube/deploy_sars_cov_2.yaml
- psga/sars_cov_2/help.nf
- psga/sars_cov_2/nextflow.config
- psga/sars_cov_2/psga.nf
Changes:
* Add new env variable to set up the main pipeline docker image. This env variable is called SARS_COV_2_PIPELINE_DOCKER_IMAGE.
Testing:
* The use of `SARS_COV_2_PIPELINE_DOCKER_IMAGE="sars-cov-2-pipeline"` was tested on minikube. This is the setting for PSGA dev
* The use of `SARS_COV_2_PIPELINE_DOCKER_IMAGE="psga-pipeline"` was tested on Jenkins (congenica account). This is the setting for Congenica ECR / Jenkins 
Testing on Minikube:
```
(venv-psga-pipeline) pierodallepezze@CONGENICA-0256:~/psga-pipeline/minikube$ k exec -it sars-cov-2-pipeline-minikube-86db564bc9-grkz5 -- bash 
root@sars-cov-2-pipeline-minikube-86db564bc9-grkz5:/app/psga# env | grep "SARS_COV_2_PIPELINE_DOCKER_IMAGE"
SARS_COV_2_PIPELINE_DOCKER_IMAGE=sars-cov-2-pipeline …
```
> PSG-1026: enable configuration of name for sars-cov-2 main docker image

- jenkins/compare.py
- jenkins/files/sars_cov_2/Jenkinsfile
- jenkins/loading.py
- jenkins/sars_cov_2.py
- jenkins/test_validation.py
- jenkins/validation.py
- minikube/cleanup.sh
- scripts/sars_cov_2/generate_pipeline_results_files.py
- tests/jenkins/test_loading.py
- tests/jenkins/test_sars_cov_2_validation.py
- tests/jenkins/util.py
- tests/sars_cov_2/test_generate_pipeline_results_files.py
**the validation script currently fails on jenkins int test - let me fix this before reviewing**
This PR fixes the paths in the resultfiles.json (`s3:/bucket/file` -> `s3://bucket/file`).
Additional test:
```
root@sars-cov-2-pipeline-minikube-86db564bc9-sr5j5:/app/psga# nextflow run . --run ont_short --sequencing_technology ont --kit ARTIC_V3 --metadata s3://synthetic-data-dev/UKHSA/small_tests/ont/metadata.csv --output_path s3://synthetic-data-dev/UKHSA/piero_test_remove
N E X T F L O W  ~  version 22.08.0-edge
Launching `./main.nf` [deadly_mandelbrot] DSL2 - revision: b450160779
[4b/9ad1fa] Submitted process > psga:pipeline_start
[0e/78081d] Submitted process > psga:check_metadata (metadata.csv)
[02/bd67aa] Submitted process > psga:stage_sample_file (1 - …
```
> PSG-1097: replace Path with str in the generation of resultfiles.json so that we can process both FS paths and S3 URIs

- docker/Dockerfile.pangolin
- docker/pangolin_environment.yml
https://github.com/snakemake/snakemake/pull/1894/files. Without this code, the installation of awscli crashes snakemake
Testing on awsbatch: 
```
(venv-psga-pipeline-3.10) pierodallepezze@CONGENICA-0256:~/psga-pipeline$ k exec -it sars-cov-2-pipeline-6c577c549-qt6dw -- bash 
root@sars-cov-2-pipeline-6c577c549-qt6dw:/app/psga# nextflow run . --run unknown_short --sequencing_technology unknown --kit none --metadata s3://psga-dev-pipeline-metadata/fb217fbc-271c-44c9-b17e-fa9497044c10.csv --output_path s3://psga-dev-results/dev/piero-out-20221005-1530 -resume
N E X T F L O W  ~  version 22.09.7-edge
Launching `./main.nf` [evil_murdock] DSL2 - revision: 9ec850e2bd
[ec/457a55] Cached process > psga:check_metadata (fb217fbc-271c-44c9-b17e-fa9497044c10.csv)
[32/bd91d0] Cached process > …
```
> PSG-1119: use snakemake 7.16.0 which includes this fix:

- docker/Dockerfile.ncov2019-artic-nf-illumina
- docker/Dockerfile.ncov2019-artic-nf-nanopore
"CAPSULE EXCEPTION: Could not parse version: 11.0.9.1-internal". This will be completely fix when nextflow is directly installed via Conda
> Pin openjdk version in conda as Nextflow complains:

- scripts/synthetic/generate_results.py
Naming the column QC breaks all the reports we have for covid. Naming it QC_Status should enable them all to work for both pathogens.
> change qc to qc_status

- docker/sars_cov_2/ncov2019-artic-nf_extras.yml
"CAPSULE EXCEPTION: Could not parse version: 11.0.9.1-internal". This will be completely fix when nextflow is directly installed via Conda
> Pin openjdk version in conda as Nextflow complains: 

- data/sars_cov_2/ncov2019-artic-nf/MN908947.3.gff
- data/sars_cov_2/ncov2019-artic-nf/SARS-CoV-2.types.yaml
- docker/Dockerfile.ncov2019-artic-nf-illumina
- docker/Dockerfile.ncov2019-artic-nf-nanopore
- psga/sars_cov_2/ncov2019_artic.nf
- psga/sars_cov_2/nextflow.config
Run ncov with genotyping optional process. 
The addition of these new files and data to the pipeline results.csv and resultfiles.json will be implemented in another ticket.
Examples of information we can extract.
**Illumina**
```
root@sars-cov-2-pipeline-minikube-6cf7cbfc9c-ntg2f:/app/psga# ls /data/output/pipeline_ci_illumina/ncov2019-artic/output_typing/*
/data/output/pipeline_ci_illumina/ncov2019-artic/output_typing/9729bce7-f0a9-4617-b6e0-6145307741d1.csq.vcf
/data/output/pipeline_ci_illumina/ncov2019-artic/output_typing/9729bce7-f0a9-4617-b6e0-6145307741d1.typing.csv
/data/output/pipeline_ci_illumina/ncov2019-artic/output_typing/9729bce7-f0a9-4617-b6e0-6145307741d1.variants.csv
root@sars-cov-2-pipeline-minikube-6cf7cbfc9c-ntg2f:/app/psga# cat …
```
> PSG-1874: run ncov2019-artic-nf using gff and yaml typing annotions

- Makefile
- data/synthetic/fastqc/limits.txt
- docker/synthetic/fastqc.yml
- psga/synthetic/nextflow.config
This update follows the refactory of the docker images.
Fastqc used to run in the sars-cov-2 and synthetic docker image, but now runs on its own docker image.
NOTE: the synthetic pipeline reuses the fastqc docker image of the sars-cov-2 pipeline. This could not be the case for other pathogens as we might want to have different fastqc versions / limits configs.
Testing: 
```
root@synthetic-pipeline-minikube-5fdb87d78b-wj68g:/app/psga# nextflow run . --run synthetic --sequencing_technology illumina --kit ARTIC_V4 --metadata /data/pipeline_ci_illumina/metadata.csv --output_path /data/output/synthetic
N E X T F L O W  ~  version 22.10.0
Launching `./main.nf` [clever_wozniak] DSL2 - revision: 9ec850e2bd
WARN: K8s namespace provided in the nextflow configuration does not match with pod …
```
> PSG-1886: update synthetic pipeline to run fastqc in its own dedicated docker container

- jenkins/sars_cov_2.py
- scripts/sars_cov_2/generate_pipeline_results_files.py
- scripts/util/slugs.py
- tests/common/test_concat_csv.py
- tests/common/test_format_genotyping.py
- tests/common/test_primer_autodetection.py
- tests/sars_cov_2/test_generate_pipeline_results_files.py
- tests/test_data/pipeline_results_files/resultfiles_illumina.json
- tests/test_data/pipeline_results_files/resultfiles_ont.json
- tests/test_data/pipeline_results_files/resultfiles_unknown.json
- tests/util/test_slugs.py
- tests/utils_tests.py
This PR has not yet been merged due to the 24/11 release.
**UPDATE**
`type` has changed. See conversation below. 
@cramshaw I replaced `png/coverage` with `png/qc` as those png files are ncov qc plots.
See: https://confluence.congenica.net/pages/viewpage.action?spaceKey=PSG&title=Pipeline+Results 
```
Example
{
"d96512bc-94d2-4b19-a311-a2da98a2aa95": [{
"type": "sars-cov-2:fasta",
"file": "reheaded-fasta/d96512bc-94d2-4b19-a311-a2da98a2aa95.fasta"
},
{
"type": "sars-cov-2:bam",
"file": "d96512bc-94d2-4b19-a311-a2da98a2aa95.bam"
},
{
"type": "sars-cov-2:vcf",
"file": "d96512bc-94d2-4b19-a311-a2da98a2aa95.vcf"
}],
"41995a81-1420-4b9c-8305-792067f11198": [{
"type": "sars-cov-2:fasta",
"file": "reheaded-fasta/41995a81-1420-4b9c-8305-792067 f11198.fasta"
},
{
"type": "sars-cov-2:bam",
"file": …
```
> PSG-1141: add file type to pipeline resultfiles.json

- .github/workflows/publish_configs.yaml
The interpolation was done using single quote so the version printed was literal `${version}`
> PSG-2003 Fixed string interpolation for docker_tag

- psga/config/psga-schema-sars-cov-2.yaml
Current columns in results.csv: 
```
SAMPLE_ID,STATUS,CONTAMINATED_READS,PRIMER_DETECTED,PRIMER_NUMREADS,PRIMER_UNIQUE_NUMREADS,PRIMER_COVERAGE,PRIMER_INPUT,NCOV_PCT_N_BASES,NCOV_PCT_COVERED_BASES,NCOV_LONGEST_NO_N_RUN,NCOV_NUM_ALIGNED_READS,NCOV_QC_PASS,PANGOLIN_LINEAGE,PANGOLIN_CONFLICT,PANGOLIN_AMBIGUITY_SCORE,PANGOLIN_SCORPIO_CALL,PANGOLIN_SCORPIO_SUPPORT,PANGOLIN_SCORPIO_CONFLICT,PANGOLIN_SCORPIO_NOTES,PANGOLIN_PANGO_DESIGNATION_VERSION,PANGOLIN_VERSION,PANGOLIN_SCORPIO_VERSION,PANGOLIN_CONSTELLATION_VERSION,PANGOLIN_IS_DESIGNATED,PANGOLIN_QC_STATUS,PANGOLIN_QC_NOTES,PANGOLIN_NOTE
```
Columns in config: 
```
psga-schema-sars-cov-2.yaml:  - field_name: sample_id
psga-schema-sars-cov-2.yaml:  - field_name: SAMPLE_ID
psga-schema-sars-cov-2.yaml:  - field_name: STATUS …
```
> PSG-2426: add contaminated reads column to sars-cov-2 config

- Makefile
- docker/Dockerfile.s-aureus
- minikube/deploy_s_aureus_pipeline.yaml
- minikube/deploy_sars_cov_2_pipeline.yaml
- minikube/deploy_synthetic_pipeline.yaml
Changes:
1. do not download reference genomes of species sharing the same genus of S-Aureus
2. remove subsampling and fetch all reference genomes for that pathogen
3. fix mamba command
4. (minor) update docker image URI
```
2023-01-23 15:49:04:root:INFO - Staphylococcus aureus verified in ENA Taxonomy database
2023-01-23 15:49:04:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2023-01-23 15:53:53:root:INFO - Setting up antimicrobial resistance datasets
2023-01-23 15:53:53:root:INFO - Setting up latest AMRFinder+ database
2023-01-23 15:54:48:root:INFO - AMRFinder+ database saved to ./datasets/antimicrobial-resistance/amrfinderdb.tar.gz
2023-01-23 15:54:48:root:INFO - Setting up MLST datasets
2023-01-23 15:54:48:root:INFO - Setting up default MLST schema for …
```
> PSG-2607: amend command `bactopia datasets`

- .github/workflows/pipeline.yaml
- Makefile
- docker/Dockerfile.htstools
- docker/sars_cov_2/htstools.yml
- psga/sars_cov_2/nextflow.config
This generic and small image (488MB) can be used for a wide range of pipeline tasks.
Note: we need to add a new ECR called `htstools` for this PR.
Testing does not show any difference as expected.
> PSG-2503: add htstools docker image containing htslib, samtools and bcftools

- psga/common/reheader.nf
- psga/sars_cov_2/ncov2019_artic.nf
- psga/sars_cov_2/nextflow.config
- psga/sars_cov_2/psga.nf
- scripts/sars_cov_2/generate_pipeline_results_files.py
- tests/test_data/pipeline_results_files/sars_cov_2/resultfiles_illumina.json
- tests/test_data/pipeline_results_files/sars_cov_2/resultfiles_ont.json
- tests/test_data/pipeline_results_files/sars_cov_2/resultfiles_unknown.json
**Changes**
In the sars-cov-2 pipelines, the tasks for reheadering/storing/standardising a fasta file occur in separate processes. This means that they require the spin up of dedicated docker containers. These processes run quickly and this way of executing them is inefficient. Actual changes:
* illumina / ont samples: the ncov process takes care of the reheadering (invoking the python script directly) of the output fasta file and publishing of this latter file
* fasta samples: the standardisation (which is actually a file renaming) and publication of reheadered fasta are accomplished by the reheadering process.
**Outcome**
For a batch of 400 samples, this change avoids the creation of 2x400 jobs.
**Testing**
The reheadered fasta is now simply a by product of ncov. If samples are fasta, …
> PSG-2471: reheader fasta files within ncov process

- poetry.lock
- pyproject.toml
Pins the versions completely, based on what we have in the psga-pipeline docker image.
(please, discard CircleCi Pipeline requirement)
> PSG-2711: pin poetry versions

- docker/Dockerfile.ncov2019-artic-nf-illumina
- docker/Dockerfile.ncov2019-artic-nf-nanopore
**Changes**
* update critical tools: `nextflow`, `bwa` and `python`. See: https://github.com/Congenica/ncov2019-artic-nf/pull/10 
* it looks like that it is no longer required to pin: `cutadapt` and `dnaio` after updating the tools above.
* `awscli` is now installed via conda
**Testing 1**
Docker images ship updated nextflow:
```
$ docker run -it --rm 566277102435.dkr.ecr.eu-west-2.amazonaws.com/congenica/psga-nonprod/ncov2019-artic-nf-illumina:dev_latest bash 
root@e79337c1b64e:/# nextflow -version
N E X T F L O W
version 22.10.0 build 5826
created 13-10-2022 05:44 UTC 
cite doi:10.1038/nbt.3820
http://nextflow.io
$ docker run -it --rm 566277102435.dkr.ecr.eu-west-2.amazonaws.com/congenica/psga-nonprod/ncov2019-artic-nf-nanopore:dev_latest bash 
root@20d528b5ab42:/# nextflow -version 
N …
```
> PSG-2603: update ncov2019-artic-nf dependencies

- docker/Dockerfile.psga-pipeline
When poetry tries to install packages, urllib3 is already installed at a latest version which is incompatible with the chosen poetry version and the poetry install fails. This replaces the urllib3 package with a version compatible with the installer.
> PSG-3287 fix build

- psga/config/psga-schema-s-aureus.yaml
- psga/config/psga-schema-sars-cov-2.yaml
- psga/config/psga-schema-synthetic.yaml
The output schema is used by the front end to provide a list of filter options. The SAMPLE_ID is not making it into the output metadata. So when the user tries to use this field to filter samples it is not working.
The sample id is in the input metadata so this can be used to successfully filter samples to a single one.
> PSG-3268: Remove SAMPLE_ID from all of the output schemas

- docker/sars_cov_2/README
- docker/sars_cov_2/fastqc.yml
- docker/sars_cov_2/htstools.yml
- docker/sars_cov_2/pangolin.yml
- docker/sars_cov_2/primer-autodetection.yml
- docker/sars_cov_2/psga.yml
- docker/sars_cov_2/read-it-and-keep.yml
- docker/synthetic/psga.yml
Before this PR, the command `nextflow run . --run ont --sequencing_technology ont --kit unknown --metadata /data/synthetic-ont/metadata.csv --tput_path /data/output/pipeline_synthetic_ont -with-report report.html -with-timeline timeline.html` failed with error:
```
Command error:
Command 'ps' required by nextflow to collect task metrics cannot be found
```
Tested using ont samples. The reports were generated and attached to the ticket.
```
root@sars-cov-2-pipeline-minikube-d85788548-wrbbx:/app/psga# nextflow run . --run ont --sequencing_technology ont --kit unknown --metadata /data/synthetic-ont/metadata.csv --tput_path /data/output/pipeline_synthetic_ont -with-report report.html -with-timeline timeline.html
N E X T F L O W  ~  version 22.10.0
Launching `./main.nf` [special_cori] DSL2 - …
```
> PSG-3615: add procps dependency which is required in order to generate nextflow reports

- .github/workflows/check_and_test.yaml
- .github/workflows/pipeline.yaml
- .github/workflows/release_branch.yml
- .github/workflows/test_traceability.yml
- poetry.lock
- pyproject.toml
- tests/common/test_check_metadata.py
- tests/common/test_concat_csv.py
- tests/common/test_contamination_removal.py
- tests/common/test_fetch_primers.py
- tests/common/test_primer_autodetection.py
- tests/common/test_reheader_fasta.py
- tests/integration_tests/test_compare.py
- tests/integration_tests/test_loading.py
- tests/integration_tests/test_validation.py
- tests/sars_cov_2/test_extract_typing_data.py
- tests/sars_cov_2/test_generate_pipeline_results_files_sars_cov_2.py
- tests/synthetic/test_generate_pipeline_results_files_synthetic.py
- tests/util/test_convert.py
- tests/util/test_logging.py
- tests/util/test_notification.py
- tests/util/test_slugs.py
This PR enables test traceability on this repo, allowing all tests for the PSGA pipeline to be traced back to Jira work items. It's worth noting that the approach here is identical to how tests are managed in all other PSGA focused repos.
A few notes:
- This PR just focuses on the GitHub Actions pipeline; the CircleCI pipeline will come in a second PR
- I've added `allure-pytest` as a dependency to the project, allowing `pytest` to generate a set of Allure Results that are then copied to an S3 bucket
- A new `test_traceability` workflow has been added to GitHub Actions, which:
- Only parses the results generated on non-release branches to check they are valid and can be ingested by the test traceability framework
- Goes one step further for release branches and records the results of the …
> PSG-3579: Add Allure to unit tests for test traceability

- .github/workflows/pipeline.yaml
- .github/workflows/release_branch.yml
This PR changes the tracing of tests back to Jira on builds of the tests from `main`. It was originally from `release/*` branches but it's much more useful to have the tracing to Jira executed after we've merged to `main` as we can then generate traceability reports ahead of the release (instead of having to wait for a `release/*` branch to be created).
It also removes a step from the release workflow in GitHub Actions and reduces the risk of something going wrong at that stage.
No need as the change is minimal and I've confirmed that this identical syntax works for the `psga-backend` repo in [this PR](https://github.com/Congenica/psga-backend/pull/894).
> Fix: Trace tests back to Jira on builds from `main`

- .github/workflows/test_traceability.yml
It looks like the `Analysis` component has been deleted in Jira and replaced with `Pipelines`, which broke the workflow when merging to `main`. This PR updates the test traceability workflow to create test executions with this new component instead.
> Fix: Update test traceability component from Analysis to be Pipelines

- .github/workflows/test_traceability.yml
The test traceability framework expects tests in Xray to be under a `{repo_name}/{test_type}` structure. For example:
- `psga-backend/unit`
- `psga-system-testing/scalability`
The `psga-pipeline` tests did not have a `test_type` declared in the config.
> Fix: Test traceability repository path

- psga/common/help.nf
- psga/common/organise_metadata_sample_files.nf
- psga/main.nf
This is with the aim to remove references to --metadata so we can remove it from the system
This would simplify how the how the pipelines are run
> PSG-4630 Changing reference to --metadata to --config-path 

- psga/common/help.nf
- psga/common/organise_metadata_sample_files.nf
- psga/main.nf
The --config-path argument is now always passed to pipelines. 
We should use it in the sars-cov-2 pipeline to locate the samples.csv file. This is reducing the usage of the 
--metdata commend line argument so it can be removed.
The point of this is that the --config-path argument is more extensible as we can add additional files to the path without having to modifying the command line execution model or pipelines that aren't interested in additional files.
(so for settings, we can just write a settings file in the --config-path directory and those pipelines that are interested can use it)
> PSG-4630 Find samples.csv via --config-path

- .github/workflows/check_and_test.yaml
- .github/workflows/test_traceability.yml
I've wanted to centralise the storing of test evidence from all Congenica products in a single S3 bucket. This will allow the generation of reports around test evidence to be centralised and automated more easily.
I [requested a new bucket](https://jira.congenica.net/browse/SAP-34143) from the Ops team, which they created a while ago. This bucket is reachable from the Congenica dev AWS account (144563655722) and from the PSGA dev AWS account (566277102435), meaning the:
- Pods that Jenkins spins up in clusters that belong to either account can read from and write to this bucket.
- GitHub runners on the PSGA side can read from and write to this bucket.
Therefore, this PR updates the S3 bucket in the GitHub Actions workflow where the Allure Results are uploaded to and where the test …
> RT-363: Update GitHub workflows to upload Allure Results to new S3 bucket
